In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [4]:
numbers = np.array([10, 20, 30, 40, 50])
print(numbers)
print(type(numbers))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [6]:
#if we put different data types in the simple list, 
#it will not convert them to a common data type.
my_list = [1,2,"ALi",4,5]
print(my_list)
print(type(my_list))
#But if we put different data types in the numpy array,
#it will convert all of them to a common data type.
my_numpy_array = np.array(my_list)
print(my_numpy_array)
print(type(my_numpy_array))


[1, 2, 'ALi', 4, 5]
<class 'list'>
['1' '2' 'ALi' '4' '5']
<class 'numpy.ndarray'>


In [7]:
#Accessing elements in a numpy array
#Indexing and slicing works the same way as in Python lists.
print(numbers[0]) # Accessing the first element
print(numbers[-1]) # Accessing the last element
print(numbers[1:4]) # Accessing elements from index 1 to 3

10
50
[20 30 40]


In [10]:
#Modifying elements in a numpy array
numbers[1]= 80
print(numbers) # Output: [10 80 30 40 50]
print(len(numbers))

#Shape of a numpy array
#The shape of a numpy array is a tuple that represents
# the dimensions of the array.
print(numbers.shape)

[10 80 30 40 50]
5
(5,)


In [15]:
# Data Types of Elements
# dtype tell us the data type stored inside in the array.
print(numbers.dtype)

# Adding number to each element in the array
numbers = numbers + 5
print(numbers) 
# In the same way we can do Multipication, Division, 
# Subtraction, etc. with the array.

int64
[25 95 45 55 65]


In [24]:
# Adding two arrays
array_1 = np.array([2,4,6])
array_2 = np.array([3,5,7])
print(array_1 + array_2) 
# In this way we can do Multipication, Division, 
# Subtraction, etc. with the two arrays.

# SUM of all elements in the array
print(np.sum(numbers))
print(np.mean(numbers))
print(np.max(numbers))
print(np.min(numbers))

[ 5  9 13]
285
57.0
95
25


In [30]:
zeros = np.zeros((3,4))
print(zeros)
ones = np.ones((2,3))
print(ones)

#Creating Numbers Using arrange
arange_number = np.arange(0, 11)
print(arange_number)
even = np.arange(2,21,2)
print(even)
odd = np.arange(1,22,2)
print(odd)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[ 1  3  5  7  9 11 13 15 17 19 21]
