Creating a 2D-Array which contain rows and coloumns
It is similar to table or matrix

In [2]:
import numpy as np

In [6]:
students = np.array([["Bilal", "Ali", "Ahmad"], [90, 92, 88], ["CS", "SE", "AI"]])
print(students)
print(students.ndim) #Dimension
print(students.shape) #Shape
print(students.size) #Size
print(students.dtype) #Data Type

[['Bilal' 'Ali' 'Ahmad']
 ['90' '92' '88']
 ['CS' 'SE' 'AI']]
2
(3, 3)
9
<U21


In [12]:
#Accessing complete row
print(students[0]) 
print(students[2])

#Accessing complete column
print(students[:, 0])

#Accessing specific element
#Syntax: array[row_index, column_index]
print(students[0][2])
print(students[2][1])

['Bilal' 'Ali' 'Ahmad']
['CS' 'SE' 'AI']
['Bilal' '90' 'CS']
Ahmad
SE


In [17]:
students[0][1]= "Ayesha"
print(students)

#Slicing row
print(students[0:2])
print(students[:, 0:2]) #Slicing column

[['Bilal' 'Ayesha' 'Ahmad']
 ['90' '92' '88']
 ['CS' 'SE' 'AI']]
[['Bilal' 'Ayesha' 'Ahmad']
 ['90' '92' '88']]
[['Bilal' 'Ayesha']
 ['90' '92']
 ['CS' 'SE']]


Reshaping An Array

In [20]:
number = np.array([10, 20, 30, 40, 50, 60])
print(number)
matrix = number.reshape(2,3)
print(matrix)

[10 20 30 40 50 60]
[[10 20 30]
 [40 50 60]]


Flattening An Array

In [22]:
matrix_1 = np.array([[1,2,3], [4,5,6]])
print(matrix_1)
flat = matrix.flatten()
print(flat)

[[1 2 3]
 [4 5 6]]
[10 20 30 40 50 60]


In [5]:
value1 = np.random.randint(4, 10, (2,2))
print(value1)
value2 = np.random.rand(3,3)
print(value2)
print(np.sqrt(value1))

[[9 6]
 [9 8]]
[[0.21138942 0.96457587 0.67676769]
 [0.2924563  0.5928663  0.4133811 ]
 [0.70324332 0.87992098 0.25429603]]
[[3.         2.44948974]
 [3.         2.82842712]]
